<a href="https://colab.research.google.com/github/STNox/Deep-Learning/blob/master/2.%20Model/02_%ED%94%BC%EB%A7%88_%EC%9B%90%EC%A3%BC%EB%AF%BC_%EB%8B%B9%EB%87%A8%EB%B3%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 피마 원주민 당뇨병

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
seed = 2021
np.random.seed(seed)
tf.random.set_seed(seed)

### 데이터 전처리

In [ ]:
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
Data_set = np.loadtxt(filename, delimiter=',')
Data_set[:3, :]

Saving pima-indians-diabetes.csv to pima-indians-diabetes.csv


array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ,   0.   ],
       [  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ,   1.   ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_norm = scaler.fit_transform(Data_set[:, :-1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, Data_set[:, -1], stratify=Data_set[:, -1], random_state=seed)
X_train.shape, X_test.shape

((576, 8), (192, 8))

### 모델 정의, 설정, 학습, 평가

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential([
                    Dense(12, input_shape=(8,), activation='relu'),
                    Dense(8, activation='relu'),
                    Dense(1, activation='sigmoid')
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=200, validation_split=0.2, batch_size=20)

Epoch 1/200
23/23 [==============================] - 1s 17ms/step - loss: 0.6485 - accuracy: 0.6219 - val_loss: 0.5971 - val_accuracy: 0.6379
Epoch 2/200
23/23 [==============================] - 0s 3ms/step - loss: 0.6003 - accuracy: 0.6959 - val_loss: 0.5717 - val_accuracy: 0.6638
Epoch 3/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5720 - accuracy: 0.6904 - val_loss: 0.5540 - val_accuracy: 0.6293
Epoch 4/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5450 - accuracy: 0.7372 - val_loss: 0.5456 - val_accuracy: 0.6466
Epoch 5/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5559 - accuracy: 0.7276 - val_loss: 0.5397 - val_accuracy: 0.6810
Epoch 6/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5248 - accuracy: 0.7505 - val_loss: 0.5348 - val_accuracy: 0.6724
Epoch 7/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5081 - accuracy: 0.7467 - val_loss: 0.5307 - val_accuracy: 0.6983
Epoch 8/200


In [ ]:
acc = model.evaluate(X_test, y_test)
acc

6/6 [==============================] - 0s 2ms/step - loss: 0.5618 - accuracy: 0.7812


[0.5617662668228149, 0.78125]

### 테스트

In [ ]:
index = 10
test_data = X_test[index, :].reshape(1, -1)
test_data

array([[-0.54791859,  2.38188392,  0.04624525,  4.92186584, -0.69289057,
         0.34362394,  0.31144581,  2.44704844]])

In [ ]:
label = y_test[index]
int(label)

1

In [ ]:
pred = model.predict(test_data)
pred

array([[0.8747372]], dtype=float32)

In [ ]:
int(pred[0][0] > 0.5)

1

### 은닉층 추가

In [ ]:
model2 = Sequential([
                     Dense(24, input_shape=(8, ), activation='relu'),
                     Dense(12, activation='relu'),
                     Dense(8, activation='relu'),
                     Dense(1, activation='sigmoid')
])
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 24)                216       
_________________________________________________________________
dense_8 (Dense)              (None, 12)                300       
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 9         
Total params: 629
Trainable params: 629
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, batch_size=20, epochs=200, validation_split=0.2)

Epoch 1/200
23/23 [==============================] - 0s 5ms/step - loss: 0.2779 - accuracy: 0.8870 - val_loss: 0.8145 - val_accuracy: 0.7155
Epoch 2/200
23/23 [==============================] - 0s 3ms/step - loss: 0.2788 - accuracy: 0.8870 - val_loss: 0.8225 - val_accuracy: 0.6983
Epoch 3/200
23/23 [==============================] - 0s 3ms/step - loss: 0.2770 - accuracy: 0.8913 - val_loss: 0.8137 - val_accuracy: 0.7241
Epoch 4/200
23/23 [==============================] - 0s 3ms/step - loss: 0.2761 - accuracy: 0.8913 - val_loss: 0.8173 - val_accuracy: 0.7241
Epoch 5/200
23/23 [==============================] - 0s 3ms/step - loss: 0.2747 - accuracy: 0.8913 - val_loss: 0.8222 - val_accuracy: 0.6983
Epoch 6/200
23/23 [==============================] - 0s 3ms/step - loss: 0.2754 - accuracy: 0.8935 - val_loss: 0.8271 - val_accuracy: 0.7069
Epoch 7/200
23/23 [==============================] - 0s 3ms/step - loss: 0.2743 - accuracy: 0.8891 - val_loss: 0.8219 - val_accuracy: 0.7241
Epoch 8/200
2

In [ ]:
acc = model2.evaluate(X_test, y_test)
acc

6/6 [==============================] - 0s 2ms/step - loss: 0.6448 - accuracy: 0.6679


[0.6576449275016785, 0.6510416865348816]